# Generated by Django 2.1.7 on 2019-04-10 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0002_auto_20190410_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
