# Generated by Django 2.1.7 on 2019-04-10 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0003_auto_20190410_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamaMeetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetings', to='chama.Chama')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_requests', to='chama.Chama')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['id']},
        ),
    ]
