# Generated by Django 2.1.7 on 2019-04-10 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0004_auto_20190410_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamameetings',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='loanrequests',
            options={'ordering': ['id']},
        ),
    ]
