# Generated by Django 2.1.7 on 2019-04-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0005_auto_20190410_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequests',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chamameetings',
            name='location',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
